version: "3.9"
services:
  app:
    build: .
    ports:
      - 5000:5000
    links:
      - prometheus
    volumes:
      - ./:/app
  
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - '--storage.tsdb.path=/prometheus'

  cadvisor:
    image: google/cadvisor:latest
    container_name: monitoring_cadvisor
    volumes:
      - /:/rootfs:ro # ro: read only (container read from host only)
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    expose:
      - 9100

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    ports:
      - 3010:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  grafana-dashboard:
    image:  alpine:3.10
    container_name: grafana_dashboard
    depends_on:
      - grafana
    env_file:
      - .env
    volumes:
      - ./grafana-data:/grafana
    stdin_open: true
    tty: true
    command: >
      /bin/sh -c "
        apk add --no-cache curl
        echo 'waiting for grafana'
        sleep 45s
        cd /grafana
        curl --request POST http://grafana:3000/api/datasources -u ${GRAFANA_USERNAME}:${GRAFANA_PASSWORD} --header 'Content-Type: application/json' -d @datasources/datasources.json
        curl --request POST http://grafana:3000/api/dashboards/db -u ${GRAFANA_USERNAME}:${GRAFANA_PASSWORD} --header 'Content-Type: application/json' -d @dashboards/python_dashboard.json
        curl --request POST http://grafana:3000/api/dashboards/db -u ${GRAFANA_USERNAME}:${GRAFANA_PASSWORD} --header 'Content-Type: application/json' -d @dashboards/cadvisor-exporter_rev1.json
        curl --request POST http://grafana:3000/api/dashboards/db -u ${GRAFANA_USERNAME}:${GRAFANA_PASSWORD} --header 'Content-Type: application/json' -d @dashboards/node-exporter-full_rev31.json"

volumes:
  prometheus-data:
    driver: local
  
  grafana_data:
    driver: local


