global:
  scrape_interval:     15s 
  evaluation_interval: 20s 
  external_labels:
      monitor: 'my-project'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 

  - job_name: 'myapp'
    scrape_interval: 10s
    static_configs:
      - targets: ['app:5000'] 

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']